"""Config-driven collection protocols (multi-kind).

State for the built-in ``collection_dialogue`` kind lives in
``session_state["collection"]`` and is persisted with the Agno session row.

Enable by publishing ``agno_agent.workflow`` as::

    {
      "kind": "collection_dialogue",
      "schema": {...},
      "required_actions": [...]
    }

Or nest under ``workflow.collection``. Domain policy belongs in the published
agent prompts / ``probe.goal`` — not in these modules.

To add another kind, create ``kinds/<name>/`` with a ``kind.py`` that registers
``extract_config`` via :func:`registry.register_config_extractor`, then export
kind-specific helpers from that package.
"""
from __future__ import annotations

from agno_worker.tenant.collection.registry import (
    is_collection_enabled,
    register_config_extractor,
    resolve_collection_config,
    resolve_kind,
)
from agno_worker.tenant.collection.kinds.dialogue import (
    COLLECTION_STATE_KEY,
    KIND,
    OPENING_POLICY_FIRST_TURN,
    OPENING_POLICY_OPTIONAL,
    PHASE_COLLECTING,
    PHASE_CONFIRMED,
    PHASE_DONE,
    PHASE_INIT,
    PHASE_PROBING,
    PHASE_READY,
    STATUS_MARKER_PREFIX,
    STATUS_MARKER_SUFFIX,
    advance_collection_phase,
    append_probe_note,
    append_status_marker,
    apply_ask_quality_tracking,
    apply_metadata_flags,
    apply_probe_salvage_and_nudge,
    apply_required_actions_from_run,
    apply_schema_exports,
    apply_scripts_progress_from_run,
    ask_batch_size,
    build_collection_tools,
    collection_instructions_appendix,
    collection_status_payload,
    compute_missing,
    confirm_collection,
    confirm_required,
    current_required_action,
    empty_collection_state,
    ensure_collection_state,
    extract_successful_tool_names,
    field_is_after_probe,
    filter_collection_gated_tools,
    finish_probe,
    format_status_marker,
    get_collection_state,
    hard_gated_tool_names,
    is_probe_active,
    is_field_probe_active,
    is_probe_finished,
    is_probe_ready,
    load_schema_into_state,
    mark_collection_done,
    normalize_schema_fields,
    normalize_field_probe,
    patient_ask_quality_issues,
    pending_required_actions,
    pending_required_action_tools,
    pre_probe_field_names,
    probe_max_rounds,
    reconcile_inline_schema_from_config,
    record_action_done,
    reply_action_fields,
    required_action_auto_mark_done,
    required_action_key,
    required_actions_mode,
    required_action_when_met,
    resolve_inline_schema_fields,
    resolve_field_probe,
    resolve_probe_config,
    resolve_required_actions,
    resolve_scripts_config,
    sanitize_patient_visible_reply,
    schema_field_names,
    schema_source,
    set_collection_state,
    snapshot_collection_for_log,
    store_collection_draft,
    suggested_write_tool,
    sync_collection_into_session_state,
    update_collected_fields,
    workflow_from_run_context,
)

__all__ = [
    "COLLECTION_STATE_KEY",
    "KIND",
    "OPENING_POLICY_FIRST_TURN",
    "OPENING_POLICY_OPTIONAL",
    "PHASE_COLLECTING",
    "PHASE_CONFIRMED",
    "PHASE_DONE",
    "PHASE_INIT",
    "PHASE_PROBING",
    "PHASE_READY",
    "STATUS_MARKER_PREFIX",
    "STATUS_MARKER_SUFFIX",
    "advance_collection_phase",
    "append_probe_note",
    "append_status_marker",
    "apply_ask_quality_tracking",
    "apply_metadata_flags",
    "apply_probe_salvage_and_nudge",
    "apply_required_actions_from_run",
    "apply_schema_exports",
    "apply_scripts_progress_from_run",
    "ask_batch_size",
    "build_collection_tools",
    "collection_instructions_appendix",
    "collection_status_payload",
    "compute_missing",
    "confirm_collection",
    "confirm_required",
    "current_required_action",
    "empty_collection_state",
    "ensure_collection_state",
    "extract_successful_tool_names",
    "field_is_after_probe",
    "filter_collection_gated_tools",
    "finish_probe",
    "format_status_marker",
    "get_collection_state",
    "hard_gated_tool_names",
    "is_collection_enabled",
    "is_probe_active",
    "is_field_probe_active",
    "is_probe_finished",
    "is_probe_ready",
    "load_schema_into_state",
    "mark_collection_done",
    "normalize_schema_fields",
    "normalize_field_probe",
    "patient_ask_quality_issues",
    "pending_required_actions",
    "pending_required_action_tools",
    "pre_probe_field_names",
    "probe_max_rounds",
    "reconcile_inline_schema_from_config",
    "record_action_done",
    "register_config_extractor",
    "reply_action_fields",
    "required_action_auto_mark_done",
    "required_action_key",
    "required_actions_mode",
    "required_action_when_met",
    "resolve_collection_config",
    "resolve_inline_schema_fields",
    "resolve_field_probe",
    "resolve_kind",
    "resolve_probe_config",
    "resolve_required_actions",
    "resolve_scripts_config",
    "sanitize_patient_visible_reply",
    "schema_field_names",
    "schema_source",
    "set_collection_state",
    "snapshot_collection_for_log",
    "store_collection_draft",
    "suggested_write_tool",
    "sync_collection_into_session_state",
    "update_collected_fields",
    "workflow_from_run_context",
]
