{{- if and .Values.nacos.enabled (eq .Values.nacos.mode "managed") }}
{{- $db := .Values.nacos.database | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiclaw.nacos.fullname" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- $comp := dict "root" . "component" "nacos" }}
    {{- include "hiclaw.component.labels" $comp | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ $db.username | quote }}
  DB_PASSWORD: {{ $db.password | quote }}
{{- end }}
