## 以下 ingress 配置将通过 Controller 调 Higress Console API 完成，这里只做临时验证
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __WORKER_NAME__-chatai
  labels:
    app.kubernetes.io/name: __WORKER_NAME__
    app.kubernetes.io/component: chatai
spec:
  ingressClassName: higress
  rules:
    - host: worker-__WORKER_NAME__-local.hiclaw.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: __WORKER_NAME__-chatai
                port:
                  number: 8642

---
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: __WORKER_NAME__-chatai-key-auth
  labels:
    app.kubernetes.io/name: __WORKER_NAME__
    app.kubernetes.io/component: chatai
spec:
  defaultConfig:
    global_auth: false
    consumers:
      - name: __WORKER_NAME__-chatai
        credential: __API_SERVER_KEY__
    keys:
      - Authorization
      - x-api-key
    in_header: true
    in_query: true
  matchRules:
    - ingress:
        - __NAMESPACE__/__WORKER_NAME__-chatai
      config:
        allow:
          - __WORKER_NAME__-chatai
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/key-auth:1.0.0